### ISSUE TITLE
Proxy/User Agent Rotation

### ISSUE THREAD

**Issue by Handsomekaizer** [TheAlphaReturns/inertia#12]
Hello sir 
I like your work and I wanted to make a suggestion. Can you please make the proxy and user agent rotate on every request.
Thank you

**Comment by TheAlphaReturns** [comment]
I might rotate user-agents but can't do proxy, only have one server. If I do make this, it will be part of a big update to the backend, which I don't have planned.

**Comment by Lukas-Batema** [comment]
> I might rotate user-agents but can't do proxy, only have one server. If I do make this, it will be part of a big update to the backend, which I don't have planned.

Why can't you make more than one server on Railway? I'm sure you can, with multiple projects. This is assuming you still use Railway.

**Comment by Handsomekaizer** [comment]
Ok thanks anyway

**Comment by Handsomekaizer** [comment]
The reason I needed the rotating user agent and proxy was so that I can use
it to send traffic to a site. But If you can help me create one it would be
nice
Thanks again

**Comment by TheAlphaReturns** [comment]
i have multiple servers on railway
check the discord.

**Comment by Lukas-Batema** [comment]
> i have multiple servers on railway check the discord.

Then why does having only one server be a restraint?

> I might rotate user-agents but can't do proxy, only have **one server**. If I do make this, it will be part of a big update to the backend, which I don't have planned.

I am just trying to give a suggestion and help brainstorm possibilities to do this.

**Comment by TheAlphaReturns** [comment]
inertia-heroku.herokuapp.com
definatleygoogleclassroom.up.railway.app (don't ask)

anyway im closing this. a new backend is planned which nukes most customization, but I will see what I can do with server rotation. Most likely, I will have a system where you can choose which backend server the frontend redirects you to.

see more at github.com/inertia-unblocker/inertia-server
