### ISSUE TITLE
captcha not working

### ISSUE THREAD

**Issue by terabyte3** [TheAlphaReturns/inertia#18]
![image](https://user-images.githubusercontent.com/73202594/154125020-0c58752b-12f1-49dd-85d3-86f66a97e3b8.png)

as you can see, on discord, hCaptchas don't work. haven't tried to reprod on any other sites yet, and i'm hosting my own instance on heroku as railway is blocked.

**Comment by Doomcow500** [comment]
Hello and thank you for the bug report,
We are currently in development of a new version of inertia which includes the corrosion proxy which should fix this issue as well as other known bugs such as YouTube, it's located at https://GitHub.com/inertia-proxy but doesn't have a functional frontend yet (I'm working on it though)

**Comment by TheAlphaReturns** [comment]
as for now, use the qr.
